### PR TITLE
Implement getting the notification icon using downloadTask

### LINKED ISSUE #17: Show app icon on the notification
Currently the app shows Soduto icon for every notification, it would look a lot more seamless if it rather used the app's own icon like kdeconnect does on linux desktop.

### PR DESCRIPTION
**Pull request by sidevesh**
I implemented some logic based on the discussion you had linked to https://github.com/soduto/Soduto/issues/29#issuecomment-1568921122
I have pretty much no experience with swift so this may be very rough but I have implemented the logic to the best of my understanding based on what I saw in Share service.
@sannidhyaroy does this make sense ?
I haven't been able to test since when running `carthage update --platform macOS --use-xcframeworks` to get the project setup,
I am getting this error:
```
...
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/sidevesh/Projects/OSS/Soduto/Carthage/Checkouts/CleanroomLogger/CleanroomLogger.xcodeproj -scheme CleanroomLogger -configuration Release -derivedDataPath /Users/sidevesh/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3.1_14E300c/CleanroomLogger/4d40edc8586c2b6b0e9e0a2ae7cf4c5a5376fe80 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/jz/rwrjfm4n2zdg_w9rw5fwgfkh0000gn/T/CleanroomLogger SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/sidevesh/Projects/OSS/Soduto/Carthage/Checkouts/CleanroomLogger)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/jz/rwrjfm4n2zdg_w9rw5fwgfkh0000gn/T/carthage-xcodebuild.6Ndcqw.log
```

The log file says:
```
...
The following build commands failed:
	Ld /Users/sidevesh/Library/Caches/org.carthage.CarthageKit/DerivedData/14.3.1_14E300c/CleanroomLogger/4d40edc8586c2b6b0e9e0a2ae7cf4c5a5376fe80/Build/Intermediates.noindex/ArchiveIntermediates/CleanroomLogger/IntermediateBuildFilesPath/CleanroomLogger.build/Release/CleanroomLogger.build/Objects-normal/x86_64/Binary/CleanroomLogger normal x86_64 (in target 'CleanroomLogger' from project 'CleanroomLogger')
(1 failure)
```

Closes #17

### CODE REVIEW

**Comment by sidevesh** [comment]
@sannidhyaroy can you take a look ?

**Comment by sidevesh** [comment]
@sannidhyaroy I managed to get the app running, fixed some errors and build issues with XCode 14,
had to fork a bunch of Carthage dependencies.
But I managed to get things working!
Screenshot 2023-08-16 at 9 51 44 AM

**Comment by sidevesh** [comment]
Haven't pushed the build fixes, since I am assuming you have things working already for pushing new builds.
Have marked this as Ready for review.

**Comment by sidevesh** [comment]
https://github.com/lukakerr/Swift-NSUserNotificationPrivate also this might allow us to have the custom icon be shown as the main icon in the notification

**Comment by sidevesh** [comment]
@sannidhyaroy I am done with making few more changes including removing the inbuilt icons, also changed the Messages and Phone icon to iOS counterparts (The blue Messaging icon was perfect so just kept that for Messages).
This is ready to test and push I think.

**Comment by sannidhyaroy** [comment]
Thank you for your work. I haven't been able to take a look at all since I have been very busy since quite a few days. I'll get back to you once I'm free...

**Comment by sannidhyaroy** [comment]
Hey, first of all I would like to thank you for working on this feature. I tried it and it seems to be fairly stable and working well. There is a minor issue that could possibly be a drawback though.
I tested with a few apps and Soduto seems to be pulling up a monotone accent app icon of the respective app.

This is how the Telegram Notification looks like:
Telegram Notification

And this is the corresponding Google Messages Notification:
Messages Notification

Most of the app icons look white (like the Telegram icon), so they look plain and simple but it gets the job done of quickly identifying from which app the notification is from. However in the second case (as with Google Messages), the app icon is indistinguishable when you're working on a black background (like you are working on GitHub or using a code editor in dark mode) and the notification arrives.

I think that we don’t have much say over this as it's a problem from the Android side of KDE Connect and Soduto will show whatever icon it receives from the other device (correct me if I'm wrong). The only solution that remains for us it to not remove the png app icons that comes along with Soduto. So, basically Soduto will show the app icon for most apps and for specific apps (like Messages) that may affect the experience, it'll use those png icons. Tell me what you think about this as well and if there could be an alternate way around...

Another thing that I noticed is that the app icon doesn’t show up if you explicitly request the other device for notifications. Like when you use the "Request Notifications" button in Soduto, it doesn’t show the app icon with the notification.

**Comment by sidevesh** [comment]
hey @sannidhyaroy , yeah that black icon does look weird, I guess I didn't notice that issue since this looks specific to the Google Messages app, I am using a Samsung phone so don't use that,
keeping icons for a set of apps does make sense to me, my only issue with that was that the icons where matched to the app name instead of the app package name,
because of that it was showing the Google Messages app icon instead of the Samsung Messages app icon,
if we can match the app icon to the package name then that won't happen so that should be fine

**Comment by sidevesh** [comment]
I never tried the `Request Notifications`  option so not sure why that has issues, wasn't sure what it was for, I thought it was maybe to request permission for notifications access or something, will have to check

**Comment by sidevesh** [comment]
> hey @sannidhyaroy , yeah that black icon does look weird, I guess I didn't notice that issue since this looks specific to the Google Messages app, I am using a Samsung phone so don't use that, keeping icons for a set of apps does make sense to me, my only issue with that was that the icons where matched to the app name instead of the app package name, because of that it was showing the Google Messages app icon instead of the Samsung Messages app icon, if we can match the app icon to the package name then that won't happen so that should be fine

Have you tried the actual kdeconnect on KDE (or gsconnect on GNOME) ? I wonder how those treat the black Google Messages icon, I am thinking that maybe it would not be a good idea to hardcode app icons into Soduto since that would diverge its behavior from KDEconnect itself, might not be a good idea

**Comment by sannidhyaroy** [comment]
> I am thinking that maybe it would not be a good idea to hardcode app icons into Soduto since that would diverge its behavior from KDEconnect itself, might not be a good idea

That actually makes sense and I agree with you. As you mentioned, it would have been better if Soduto could match app package names instead of the app name to be more specific regarding the app icon. I'll think I should take a look at how KDE Connect for macOS and Zorin Connect and GSConnect on Linux work and if they face the same issues.

**Comment by sidevesh** [comment]
I can see the icons on the notifications when I use the Request notifications option

**Comment by sannidhyaroy** [comment]
> I can see the icons on the notifications when I use the Request notifications option

Yes, it's kinda weird. Sometimes I see the icons when I use "Request Notifications" and sometimes I don't. I don't know the exact steps of reproducing when the icons don't show up as it feels kinda random but I'd request you to try to dismiss a notification when it arrives (dismiss only on macOS by using the cross button and not the "Dismiss" button that will dismiss from the source device as well), then try the "Request Notifications" button and see if the same notification arrives with a icon.

And I am confused if we should leave it as it is and just merge this PR or should we think more about the monochrome icons, in particular about app icons like Google Messages?

**Comment by sidevesh** [comment]
Its not just Request notifications, icons do seem to be missing randomly sometimes,
for some reason I think sometimes download task is missing on the payload, so I push the notification without icon,
one place I saw icons missing happen relatively consistently is when you receive a whatsapp notification for a chat and then another notification for the same chat, try that let me know if that happens for you too and happens consistently,
also the notification id that we receive is in a particular format with the package id of the app in it along with other fields,
if we can parse that then we can implement logic to handle icons specifically by package id or even cache icons to reuse in case download task is missing but we have already cached icon for that app and its particular action (notification icon may be different from the same app for different notifications),
I think all this can be subsequent prs though, including if special handling is needed for some package ids like Google Messages, that probably can only be done once parsing of notification id is implemented

**Comment by sidevesh** [comment]
I may be very wrong but I have a feeling that gsconnect / kdeconnect does not send the icon in the payload if the package id + action combination has already had a notification pushed with the icon, in that case caching would resolve this issue completely, need to check if this is actually what is happening

**Comment by sannidhyaroy** [comment]
> I may be very wrong but I have a feeling that kdeconnect does not send the icon in the payload if the package id + action combination has already had a notification pushed with the icon, in that case caching would resolve this issue completely, need to check if this is actually what is happening

Well caching might not be a completely bad idea either, given that most people have a decent amount of apps on their phones that send notifications (maybe 40? 80?). I assume it won’t consume much space and we can clean up leftover icons that aren’t used every 30 days.

But it surely does make the entire thing more complicated. Also, I noticed that the remaining icons like "Phone", "Messages" and "AirDrop" that weren’t removed doesn’t show up. Try sending a file to some other device and the transfer notification used to have the "AirDrop" icon but it doesn’t show up now.

**Comment by sidevesh** [comment]
Looks like gsconnect does do caching https://github.com/GSConnect/gnome-shell-extension-gsconnect/blob/main/src/service/plugins/notification.js#L477

Will test why the remaining icons aren't working

**Comment by sidevesh** [comment]
@sannidhyaroy for me the AirDrop icon does show up when receiving files

**Comment by sannidhyaroy** [comment]
> @sannidhyaroy for me the AirDrop icon does show up when receiving files

I just rebuilt the app from Xcode and now it does for me as well.

**Comment by sannidhyaroy** [comment]
I wished for this feature ever since I started fixing the bugs and improving some functionalities of Soduto as it would make the experience more seamless. It's very easy to know where the notification is from when you have the app icon show up than trying to read the notification title. I tried to implement this for almost 3 or 4 months but couldn't and then gave up.

Thanks for your help. Since this is still in very early stages, I'm thinking about merging this into the nightly branch. Before that, I guess we can merge the nightly into the beta (as the nightly seems to be pretty stable to not be called nightly) and we can merge the beta into the main branch (as the beta is pretty stable).

What do you think? Or should we merge this later?

**Comment by sannidhyaroy** [comment]
I've been hoping for the addition of this feature ever since I began addressing bugs and enhancing functionalities within Soduto. Introducing this feature would undeniably elevate the user experience, as having the app icon displayed along with the notification simplifies identifying its source, eliminating the need to decipher notification titles. Despite my efforts spanning around 3 to 4 months, I couldn't implement it and ultimately had gave up.

I genuinely appreciate your assistance and help, so thanks a lot. Considering the current early stage of development, I'm thinking of merging this Pull Request into the nightly branch. Prior to that step, I believe it might be sensible to merge the nightly branch into the beta, given the relative stability it has exhibited (such that the term 'nightly' doesn't accurately describe its reliability). Subsequently, we could proceed to merge the beta branch into the main one, as the beta iteration appears to have achieved a commendable level of stability.

I'm open to your insights on this approach, or if you think it would be more sensible to delay this merging process until a later point. Thank you for your time and assistance.

**Comment by sidevesh** [comment]
@sannidhyaroy thanks for the kind words! Its a small PR compared to your efforts to keep this project alive :)
I will take a look sometime this week to see if I can add parsing the notification id if I find some info about its structure and then based on that caching for icons,
I have a feeling it will improve the stability of the icons showing up in notifications and improve perf in general anyways since icons wont have to be downloaded every single time.
We should be able to merge this in at that point.

**Comment by sidevesh** [comment]
@sannidhyaroy can we get this merged in ? This has been working well for me for a while now

**Comment by sannidhyaroy** [comment]
> @sannidhyaroy can we get this merged in ? This has been working well for me for a while now

Could you give me a few more days? I haven't been able to take a look at all since I have been really busy these days with my semester exams. I will try to build it today and use it for a few days and will update you. Thank you for your patience and for your contribution to this project.

**Comment by sidevesh** [comment]
either works for me really tbh, I want to get this into the project first before taking a look at some other kdeconnect plugins that can be brought over to Soduto

**Comment by sidevesh** [comment]
@sannidhyaroy any reason this is still stuck unmerged despite our discussion earlier ? Its been stuck for 2 months now.
I want to take a look at implementing some other missing KDE COnnect plugins to add to Soduto but don't feel sure about it anymore given how long this and the other PR has been stuck.
If you are occupied with other work and not able to maintain this fork then I can take over, would really not want to start another fork though to continue work.

**Comment by sannidhyaroy** [comment]
> If you are occupied with other work and not able to maintain this fork then I can take over, would really not want to start another fork though to continue work.

That would be immensely helpful. Looking by my work schedule, it's better for me to let someone else take over this repository instead of letting it die. If you don't want to start another fork and would like to take over this repository instead, how do I give you the necessary permissions?

**Comment by sannidhyaroy** [comment]
Hey there @sidevesh,
Finally got this merged! Thanks for the help till now. Due to our previous discussion, I have invited you as a collaborator to this repository. I usually am pretty busy nowadays and only get one or two days a month to work on this project, so it'd be of a big help if you can work on this project too. However rest assured, I'll be helping in whatever way I can (although it might be delayed in some cases). Handling this project alone and managing my work wasn’t really working out for me, especially after my vacations ended.

**Comment by sidevesh** [comment]
thanks @sannidhyaroy for merging this in and thanks for the invite!

**Pull request merged**
